# Generated by Django 3.1.6 on 2021-02-21 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AwardsAndRecognitions',
            new_name='AwardAndRecognition',
        ),
        migrations.RenameModel(
            old_name='Certifications',
            new_name='Certification',
        ),
        migrations.RenameModel(
            old_name='CommunicationLanguages',
            new_name='CommunicationLanguage',
        ),
        migrations.RenameModel(
            old_name='Competitions',
            new_name='Competition',
        ),
        migrations.RenameModel(
            old_name='ConferencesAndWorkshops',
            new_name='ConferencesAndWorkshop',
        ),
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
        migrations.RenameModel(
            old_name='Documents',
            new_name='Document',
        ),
        migrations.RenameModel(
            old_name='TestScores',
            new_name='Exam',
        ),
        migrations.RenameModel(
            old_name='Patents',
            new_name='Patent',
        ),
        migrations.RenameModel(
            old_name='PositionsOfResponsibilities',
            new_name='PositionsOfResponsibilitie',
        ),
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
        migrations.RenameModel(
            old_name='Resumes',
            new_name='Resume',
        ),
        migrations.RenameModel(
            old_name='SocialProfiles',
            new_name='SocialProfile',
        ),
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
        migrations.RenameModel(
            old_name='WorkExperiences',
            new_name='WorkExperience',
        ),
    ]
