# Generated by Django 3.1.6 on 2021-02-25 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='awardandrecognition',
            old_name='issueDate',
            new_name='issue_date',
        ),
        migrations.RenameField(
            model_name='certification',
            old_name='hasExpiry',
            new_name='has_expiry',
        ),
        migrations.RenameField(
            model_name='certification',
            old_name='issuingAuthority',
            new_name='issuing_authority',
        ),
        migrations.RenameField(
            model_name='certification',
            old_name='licenseNumber',
            new_name='license_number',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='fromDate',
            new_name='from_date',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='instituteName',
            new_name='institute_name',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='toDate',
            new_name='to_date',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='associatedWith',
            new_name='associated_with',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='courseCode',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='gradeSecured',
            new_name='grade_secured',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='associatedWith',
            new_name='associated_with',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='examDate',
            new_name='exam_date',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='scoreFormat',
            new_name='score_format',
        ),
        migrations.RenameField(
            model_name='patent',
            old_name='filingDate',
            new_name='filing_date',
        ),
        migrations.RenameField(
            model_name='positionsofresponsibility',
            old_name='fromDate',
            new_name='from_date',
        ),
        migrations.RenameField(
            model_name='positionsofresponsibility',
            old_name='organizationName',
            new_name='organization_name',
        ),
        migrations.RenameField(
            model_name='positionsofresponsibility',
            old_name='toDate',
            new_name='to_date',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='endDate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='startDate',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='isLatest',
            new_name='is_latest',
        ),
        migrations.RenameField(
            model_name='semester',
            old_name='gradeSheetLink',
            new_name='grade_sheet_link',
        ),
        migrations.RenameField(
            model_name='semester',
            old_name='numberOfBacklogs',
            new_name='number_of_backlogs',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='careerPlans',
            new_name='career_plans',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='entryNumber',
            new_name='entry_number',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='fatherName',
            new_name='father_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='isVerified',
            new_name='is_verified',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='motherName',
            new_name='mother_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='preferredProfile',
            new_name='preferred_profile',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='technicalSkills',
            new_name='technical_skills',
        ),
        migrations.RenameField(
            model_name='workexperience',
            old_name='compensationMax',
            new_name='compensation_max',
        ),
        migrations.RenameField(
            model_name='workexperience',
            old_name='compensationMin',
            new_name='compensation_min',
        ),
        migrations.RenameField(
            model_name='workexperience',
            old_name='endDate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='workexperience',
            old_name='jobTitle',
            new_name='job_title',
        ),
        migrations.RenameField(
            model_name='workexperience',
            old_name='starDate',
            new_name='start_date',
        ),
        migrations.AlterField(
            model_name='awardandrecognition',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awardAndRecognition', to='student.student'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification', to='student.student'),
        ),
        migrations.AlterField(
            model_name='class',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clas', to='student.student'),
        ),
        migrations.AlterField(
            model_name='communicationlanguage',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communicationLanguage', to='student.student'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition', to='student.student'),
        ),
        migrations.AlterField(
            model_name='conferencesandworkshop',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conferenceAndWorkshop', to='student.student'),
        ),
        migrations.AlterField(
            model_name='course',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='student.student'),
        ),
        migrations.AlterField(
            model_name='document',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='student.student'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='student.student'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patent', to='student.student'),
        ),
        migrations.AlterField(
            model_name='positionsofresponsibility',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positionsOfResponsibility', to='student.student'),
        ),
        migrations.AlterField(
            model_name='project',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='student.student'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='student.student'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester', to='student.student'),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socialProfile', to='student.student'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workExperience', to='student.student'),
        ),
    ]
