# Generated by Django 3.1.6 on 2021-03-03 21:02

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210225_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='link',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='link',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='number',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='grade_sheet_link',
        ),
        migrations.AddField(
            model_name='document',
            name='document',
            field=models.FileField(null=True, upload_to='', verbose_name=student.models.get_document_upload_path),
        ),
        migrations.AddField(
            model_name='resume',
            name='name',
            field=models.CharField(default='resume1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='resume',
            field=models.FileField(null=True, upload_to=student.models.get_resume_upload_path),
        ),
        migrations.AddField(
            model_name='semester',
            name='grade_sheet',
            field=models.FileField(null=True, upload_to=student.models.get_grade_sheet_upload_path),
        ),
        migrations.AlterField(
            model_name='institute',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='logos'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True),
        ),
    ]
