# Generated by Django 3.1.6 on 2021-02-21 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210221_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conferencesandworkshop',
            old_name='organizor',
            new_name='organizer',
        ),
    ]
