# Generated by Django 3.1.6 on 2021-03-06 07:02

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20210304_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(null=True, upload_to=student.models.get_document_upload_path),
        ),
    ]
