# Generated by Django 3.1.6 on 2021-02-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20210221_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationlanguage',
            name='proficiency',
            field=models.CharField(choices=[('1', 'Elementary proficiency'), ('2', 'Limited working proficiency'), ('3', 'Professional working proficiency'), ('4', 'Full professional working proficiency'), ('5', 'Native or bilingual proficiency')], max_length=20),
        ),
    ]
