# Generated by Django 3.1.6 on 2021-02-21 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20210221_1507'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='class',
            table='Classes',
        ),
    ]
