# Generated by Django 3.1.6 on 2021-02-21 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20210221_1512'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='class',
            table=None,
        ),
    ]
