# Generated by Django 3.1.6 on 2021-04-04 14:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20210315_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.IntegerField(default=2020, validators=[django.core.validators.MinValueValidator(2000)]),
        ),
        migrations.AddField(
            model_name='student',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_verified',
            field=models.CharField(choices=[('U', 'Unverified'), ('V', 'Verified'), ('R', 'Rejected')], default='U', max_length=1),
        ),
    ]
