# Generated by Django 3.1.6 on 2021-02-21 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0009_auto_20210222_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='associatedWith',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='associatedWith',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='institute',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='student.institute'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='auth.user'),
            preserve_default=False,
        ),
    ]
