# Generated by Django 3.1.6 on 2021-04-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20210404_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardandrecognition',
            name='verification_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='verification_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='class',
            name='verification_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='verification_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='conferencesandworkshop',
            name='verification_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='verification_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='verification_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='verification_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patent',
            name='verification_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='positionsofresponsibility',
            name='verification_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='verification_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='verification_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='verification_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='socialprofile',
            name='verification_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='verification_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='verification_message',
            field=models.TextField(blank=True),
        ),
    ]
