# Generated by Django 3.1.6 on 2021-04-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20210404_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardandrecognition',
            name='is_verified',
            field=models.CharField(choices=[('U', 'Unverified'), ('V', 'Verified'), ('R', 'Rejected')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='certification',
            name='is_verified',
            field=models.CharField(choices=[('U', 'Unverified'), ('V', 'Verified'), ('R', 'Rejected')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='class',
            name='is_verified',
            field=models.CharField(choices=[('U', 'Unverified'), ('V', 'Verified'), ('R', 'Rejected')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='competition',
            name='is_verified',
            field=models.CharField(choices=[('U', 'Unverified'), ('V', 'Verified'), ('R', 'Rejected')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='conferencesandworkshop',
            name='is_verified',
            field=models.CharField(choices=[('U', 'Unverified'), ('V', 'Verified'), ('R', 'Rejected')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_verified',
            field=models.CharField(choices=[('U', 'Unverified'), ('V', 'Verified'), ('R', 'Rejected')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='document',
            name='is_verified',
            field=models.CharField(choices=[('U', 'Unverified'), ('V', 'Verified'), ('R', 'Rejected')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='exam',
            name='is_verified',
            field=models.CharField(choices=[('U', 'Unverified'), ('V', 'Verified'), ('R', 'Rejected')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='patent',
            name='is_verified',
            field=models.CharField(choices=[('U', 'Unverified'), ('V', 'Verified'), ('R', 'Rejected')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='positionsofresponsibility',
            name='is_verified',
            field=models.CharField(choices=[('U', 'Unverified'), ('V', 'Verified'), ('R', 'Rejected')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_verified',
            field=models.CharField(choices=[('U', 'Unverified'), ('V', 'Verified'), ('R', 'Rejected')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='resume',
            name='is_verified',
            field=models.CharField(choices=[('U', 'Unverified'), ('V', 'Verified'), ('R', 'Rejected')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='semester',
            name='is_verified',
            field=models.CharField(choices=[('U', 'Unverified'), ('V', 'Verified'), ('R', 'Rejected')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='is_verified',
            field=models.CharField(choices=[('U', 'Unverified'), ('V', 'Verified'), ('R', 'Rejected')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='is_verified',
            field=models.CharField(choices=[('U', 'Unverified'), ('V', 'Verified'), ('R', 'Rejected')], default='U', max_length=1),
        ),
    ]
