# Generated by Django 3.1.6 on 2021-02-22 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20210222_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardandrecognition',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awardAndRecognition', to='student.student'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification', to='student.student'),
        ),
        migrations.AlterField(
            model_name='class',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clas', to='student.student'),
        ),
        migrations.AlterField(
            model_name='communicationlanguage',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communicationLanguage', to='student.student'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition', to='student.student'),
        ),
        migrations.AlterField(
            model_name='conferencesandworkshop',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conferenceAndWorkshop', to='student.student'),
        ),
        migrations.AlterField(
            model_name='course',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='student.student'),
        ),
        migrations.AlterField(
            model_name='document',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='student.student'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='student.student'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patent', to='student.student'),
        ),
        migrations.AlterField(
            model_name='positionsofresponsibility',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positionsOfResponsibility', to='student.student'),
        ),
        migrations.AlterField(
            model_name='project',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='student.student'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='student.student'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester', to='student.student'),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socialProfile', to='student.student'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workExperience', to='student.student'),
        ),
    ]
