# Generated by Django 3.1.6 on 2021-04-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20210416_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('CSE', 'Computer Science & Engineering'), ('EE', 'Electrical Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('MME', 'Metallurgical and Materials Engineering'), ('MNC', 'Mathematics & Computing'), ('CBME', 'Center for BioMedical Engineering'), ('HSS', 'Humanities and Social Sciences'), ('P', 'Physics'), ('C', 'Chemistry'), ('M', 'Mathematics')], default='CSE', max_length=50),
        ),
    ]
