# Generated by Django 3.1.6 on 2021-02-23 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_auto_20210222_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workexperience',
            old_name='star_date',
            new_name='start_date',
        ),
    ]
