# Generated by Django 3.1.6 on 2021-02-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0002_auto_20210222_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobprofile',
            name='start_date',
            field=models.DateField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='start_date',
            field=models.DateField(blank=True, default=True),
        ),
    ]
