# Generated by Django 3.1.6 on 2021-03-13 12:12

from django.db import migrations, models
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0003_auto_20210308_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobprofile',
            name='branches_eligible',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('CSE', 'Computer Science & Engineering'), ('EE', 'Electrical Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('MME', 'Metallurgical and Materials Engineering'), ('MNC', 'Mathematics & Computing'), ('CBME', 'Center for BioMedical Engineering'), ('HSS', 'Humanities and Social Sciences'), ('P', 'Physics'), ('C', 'Chemistry'), ('M', 'Mathematics')], max_length=35),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate),
        ),
    ]
