# Generated by Django 3.1.6 on 2021-02-21 20:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0003_auto_20210222_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobprofile',
            name='start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='placement',
            name='start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
