# Generated by Django 3.1.6 on 2021-02-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0004_auto_20210222_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobprofile',
            name='branches_eligible',
            field=models.CharField(choices=[('CSE', 'Computer Science & Engineering'), ('EE', 'Electrical Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('MME', 'Metallurgical and Materials Engineering'), ('MNC', 'Mathematics & Computing'), ('CBME', 'Center for BioMedical Engineering'), ('HSS', 'Humanities and Social Sciences'), ('P', 'Physics'), ('C', 'Chemistry'), ('M', 'Mathematics')], max_length=50),
        ),
    ]
