# Generated by Django 3.1.6 on 2021-03-14 21:01

from django.db import migrations, models
import placement.models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0004_auto_20210313_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobprofile',
            name='job_description',
            field=models.FileField(blank=True, upload_to=placement.models.get_job_description_path),
        ),
    ]
