# Generated by Django 3.1.6 on 2021-03-14 21:33

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0007_auto_20210315_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobprofile',
            name='gender_allowed',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=5),
        ),
    ]
