# Generated by Django 3.1.6 on 2021-04-06 06:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0008_auto_20210315_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprofile',
            name='number_of_rounds',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
